#!/bin/bash

printf "Stage xauxi\n"
printf "  Get source\n"
printf "    boost"
printf " ok\n"
printf "    lua"
printf " ok\n"
printf "    luasocket"
printf " ok\n"
printf "    lualogging"
printf " ok\n"
printf "    luanode"
printf " ok\n"
printf "Build xauxi\n"
printf "  Build\n"
printf "    boost"
printf " ok\n"
printf "    lua"
printf " ok\n"
printf "    luasocket"
printf " ok\n"
printf "    lualogging"
printf " ok\n"
printf "    luanode"
printf " ok\n"

