#!/bin/bash
# tools
XAUXI_HOME=$HOME/workspace/xauxi
LUANODE_HOME=$XAUXI_HOME/3rdparty/LuaNode
LUANODE=$LUANODE_HOME/build/luanode
LUALOGGING_HOME=$XAUXI_HOME/3rdparty/lualogging
HTTEST=httest

BOOST_VERSION=1.55.0
LUALOGGING_VERSION=1.2.0
OPENSSL_VERSION=notyetdone
